apiVersion: extensions/v1beta1  
kind: Ingress  
metadata:  
  name: nexus-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:  
  rules:
  - host: nexus.35.205.122.35.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: nexus-service
          servicePort: 80