apiVersion: v1
kind: Secret
metadata:
  name: openldap-secrets
  namespace: openldap
type: Opaque
data:
  organizatation: "bXlvcmdhbml6YXRpb24=" #myorganization
  domain: "bXlkb21haW4=" #mydomain
  password: "bXlwYXNzd29yZA==" #mypassword