---
apiVersion: v1
kind: Service
metadata:
  name: openldap-service
  namespace: openldap
spec:
  selector:
    app: openldap
  ports:
  - name: openldap1
    protocol: TCP
    port: 389
    targetPort: 389
  - name: openldap2
    protocol: TCP
    port: 636
    targetPort: 636