apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-jira
  labels:
    app: postgres-jira
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-jira
  template:
    metadata:
      labels:
        app: postgres-jira
    spec:
      containers:
        - name: postgres-jira
          image: postgres:9.6.17
          ports:
          - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
          env:
          - name: "POSTGRES_DB"
            value: "jirasurgeondb"
          - name: "POSTGRES_USER"
            value: "jirasurgeonuser"
          - name: "POSTGRES_PASSWORD"
            value: "jira"
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-jira-pvc