apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-jira
  name: postgres-jira-service
spec:
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres-jira
  type: ClusterIP