apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-konga
  name: mysql-konga-service
spec:
  ports:
    - name: postgres
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql-konga
  type: ClusterIP