apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga
  labels:
    app: konga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konga
  template:
    metadata:
      labels:
        app: konga
    spec:
      containers:
      - name: konga
        image: pantsel/konga
        ports:
        - containerPort: 1337
        resources: {}
        env:
          - name: "POOL_SIZE"
            value: "10"
          - name: "KONGA_HOOK_TIMEOUT"
            value: "120000"
          - name: "DB_URI"
            value: "postgresql://kong:IOTkl45H7yZrOo3dwYh7@postgres-kong-service.default.svc:5432/konga"
          - name: "NODE_ENV"
            value: "production"