apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga
  labels:
    app: konga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konga
  template:
    metadata:
      labels:
        app: konga
    spec:
      containers:
      - name: konga
        image: pantsel/konga
        ports:
        - containerPort: 1337
        resources: {}
        env:
          - name: "DB_ADAPTER"
            value: "mysql"
          - name: "DB_HOST"
            value: "mysql-konga-service.default.svc"
          - name: "DB_PORT"
            value: "3306"
          - name: "DB_DATABASE"
            value: "konga"
          - name: "DB_USER"
            value: "konga"
          - name: "DB_PASSWORD"
            value: "0xxEs299BJU3tNS7ZDEL"
          - name: "NODE_ENV"
            value: "production"