apiVersion: extensions/v1beta1  
kind: Ingress  
metadata:  
  name: konga-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:  
  rules:
  - host: konga.35.205.122.35.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: konga-service
          servicePort: 1337