apiVersion: v1
kind: Service
metadata:
  labels:
    app: kong
  name: kong-service
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
    - port: 8001
      protocol: TCP
      targetPort: 8001
    - port: 8443
      protocol: TCP
      targetPort: 8443
    - port: 8444
      protocol: TCP
      targetPort: 8444
  selector:
    app: kong
  type: ClusterIP