apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-sonar
  name: postgres-sonar-service
spec:
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres-sonar
  type: ClusterIP